import { Platform, StyleSheet } from 'react-native';

import {
  colors,
  iosContinuousCurve,
  leopardPalette,
  radius,
  spacing,
  typeScale,
} from '@leopard/mobile-core';

export const styles = StyleSheet.create({
  rootContainer: {
    flex: 1,
    backgroundColor: '#FFFFFF',
    ...(Platform.OS === 'web' ? { minHeight: '100dvh' as any } : {}),
  },
  keyboardWrap: {
    flex: 1,
  },
  scrollView: {
    flex: 1,
  },
  scrollContent: {
    alignSelf: 'center',
    flexGrow: 1,
    maxWidth: 440,
    width: '100%',
    justifyContent: 'space-between',
    paddingHorizontal: spacing.lg,
    paddingTop: Platform.select({ ios: spacing.md, default: spacing.lg }),
  },
  heroSection: {
    width: '100%',
    alignItems: 'flex-start',
    paddingBottom: spacing.sm,
  },
  heroAuraSvg: {
    display: 'none',
  },
  brandHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    width: '100%',
    paddingBottom: spacing.sm,
  },
  brandRow: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  brandEmblem: {
    height: 32,
    width: 32,
  },
  brandWordmark: {
    height: 32,
    width: 120,
  },
  heroCopy: {
    width: '100%',
    marginTop: spacing.xs,
  },
  mainTitle: {
    color: '#0F172A',
    ...typeScale.largeTitle,
    fontWeight: '800',
    letterSpacing: -0.6,
    textAlign: 'left',
  },
  subTitle: {
    color: '#64748B',
    ...typeScale.subheadline,
    lineHeight: 22,
    marginTop: spacing.xxs,
    textAlign: 'left',
  },
  formCard: {
    width: '100%',
    gap: spacing.sm,
  },
  alertBox: {
    backgroundColor: leopardPalette.accentYellowBg,
    borderColor: leopardPalette.accentYellowBorder,
    borderRadius: radius.card,
    ...iosContinuousCurve,
    borderWidth: 1,
    marginBottom: spacing.xs,
    padding: spacing.sm,
  },
  alertText: {
    color: leopardPalette.accentYellowDark,
    ...typeScale.footnote,
    fontWeight: '600',
    lineHeight: 18,
  },
  errorBox: {
    backgroundColor: '#FEF2F2',
    borderColor: '#FECACA',
    borderRadius: radius.card,
    ...iosContinuousCurve,
    borderWidth: 1,
    marginBottom: spacing.xs,
    padding: spacing.sm,
  },
  errorText: {
    color: '#B91C1C',
    ...typeScale.footnote,
    fontWeight: '600',
    lineHeight: 18,
    textAlign: 'center',
  },
  fieldSection: {
    gap: spacing.xs,
  },
  labelRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  fieldLabel: {
    color: '#475569',
    ...typeScale.caption1,
    fontWeight: '700',
    textTransform: 'uppercase',
    letterSpacing: 0.4,
  },
  validBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.xxs,
    backgroundColor: '#F0FDF4',
    borderColor: '#BBF7D0',
    borderWidth: 1,
    paddingHorizontal: spacing.xs,
    paddingVertical: spacing.hairline,
    borderRadius: radius.pill,
  },
  validText: {
    ...typeScale.caption2,
    color: '#15803D',
    fontWeight: '700',
  },
  fieldHint: {
    color: '#94A3B8',
    ...typeScale.caption1,
    marginTop: spacing.xxs,
  },
  inputRow: {
    alignItems: 'center',
    backgroundColor: '#F8FAFC',
    borderColor: '#E2E8F0',
    borderRadius: radius.cardLg,
    ...iosContinuousCurve,
    borderWidth: 1.5,
    flexDirection: 'row',
    minHeight: 52,
    height: 52,
    paddingLeft: spacing.xs,
    paddingRight: spacing.xs,
    gap: spacing.xxs,
  },
  inputRowFocused: {
    borderColor: leopardPalette.primary,
    backgroundColor: '#FFFFFF',
    shadowColor: leopardPalette.primary,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.08,
    shadowRadius: 6,
    elevation: 2,
  },
  inputRowValid: {
    borderColor: '#10B981',
  },
  countryBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.xxs + spacing.hairline,
    backgroundColor: '#F1F5F9',
    paddingHorizontal: spacing.xs,
    paddingVertical: spacing.xxs + spacing.hairline,
    borderRadius: radius.cardSm - 2,
  },
  countryCode: {
    ...typeScale.subheadline,
    fontWeight: '700',
    color: '#0F172A',
    fontVariant: ['tabular-nums'],
  },
  countryChevron: {
    ...typeScale.caption2,
    color: '#64748B',
  },
  badgeDivider: {
    width: 1,
    height: 22,
    backgroundColor: '#E2E8F0',
    marginHorizontal: spacing.xxs,
  },
  textInput: {
    color: '#0F172A',
    flex: 1,
    ...typeScale.subheadline,
    fontWeight: '500',
    fontVariant: ['tabular-nums'],
    letterSpacing: 0.5,
    minWidth: 0,
    paddingVertical: 0,
    height: '100%',
    ...Platform.select({
      web: {
        outlineStyle: 'none',
        outlineWidth: 0,
      } as any,
    }),
  },
  clearBtn: {
    minHeight: 44,
    minWidth: 44,
    justifyContent: 'center',
    alignItems: 'center',
  },
  primaryBtn: {
    alignItems: 'center',
    backgroundColor: leopardPalette.primary,
    borderRadius: radius.cardLg,
    ...iosContinuousCurve,
    justifyContent: 'center',
    minHeight: 52,
    height: 52,
    paddingHorizontal: spacing.md,
    marginTop: spacing.xxs,
    shadowColor: leopardPalette.primary,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.18,
    shadowRadius: 10,
    elevation: 3,
  },
  primaryBtnDisabled: {
    backgroundColor: '#E2E8F0',
    borderColor: 'transparent',
    shadowOpacity: 0,
    elevation: 0,
  },
  primaryBtnText: {
    color: '#FFFFFF',
    ...typeScale.callout,
    fontWeight: '700',
    letterSpacing: -0.3,
    textAlign: 'center',
  },
  primaryBtnDisabledText: {
    color: '#94A3B8',
    ...typeScale.callout,
    fontWeight: '600',
  },
  loadingRow: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: spacing.xs,
  },
  orSection: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: spacing.sm,
    marginVertical: spacing.xs,
  },
  orLine: {
    backgroundColor: '#E2E8F0',
    flex: 1,
    height: 1,
  },
  orText: {
    color: '#94A3B8',
    ...typeScale.caption1,
    fontWeight: '600',
  },
  googleBtn: {
    alignItems: 'center',
    backgroundColor: '#FFFFFF',
    borderColor: '#E2E8F0',
    borderRadius: radius.cardLg,
    ...iosContinuousCurve,
    borderWidth: 1.5,
    flexDirection: 'row',
    gap: spacing.sm,
    justifyContent: 'center',
    minHeight: 50,
    height: 50,
    paddingHorizontal: spacing.md,
    shadowColor: '#0F172A',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.04,
    shadowRadius: 4,
  },
  googleIconWrap: {
    alignItems: 'center',
    justifyContent: 'center',
    height: 20,
    width: 20,
  },
  googleMark: {
    height: 18,
    width: 18,
  },
  googleBtnText: {
    color: '#0F172A',
    ...typeScale.subheadline,
    fontWeight: '600',
    textAlign: 'center',
  },
  btnDisabled: {
    opacity: 0.5,
  },
  firebaseNote: {
    color: '#94A3B8',
    ...typeScale.caption1,
    lineHeight: 18,
    marginTop: spacing.xxs,
    textAlign: 'center',
  },
  recaptcha: {
    height: 0,
    width: 0,
    overflow: 'hidden',
  },

  /* Demo Accounts Section */
  demoSection: {
    gap: spacing.sm,
    marginTop: spacing.xs,
  },
  dividerRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.sm,
  },
  demoDividerText: {
    ...typeScale.caption1,
    fontWeight: '700',
    color: '#94A3B8',
    textTransform: 'uppercase',
    letterSpacing: 0.4,
  },
  demoGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: spacing.xs,
  },
  demoCard: {
    flexBasis: '48%',
    flexGrow: 1,
    borderRadius: radius.cardLg,
    ...iosContinuousCurve,
    borderWidth: 1,
    padding: spacing.sm,
    gap: spacing.xxs + spacing.hairline,
    backgroundColor: '#FFFFFF',
  },
  demoCardGreen: {
    borderColor: colors.success.border,
    backgroundColor: colors.success.background,
  },
  demoCardBlue: {
    borderColor: leopardPalette.primaryBorder,
    backgroundColor: leopardPalette.primaryBg,
  },
  demoCardSlate: {
    borderColor: leopardPalette.cardBorder,
    backgroundColor: '#F8FAFC',
  },
  demoCardTop: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  demoRoleBadge: {
    paddingHorizontal: spacing.xs,
    paddingVertical: spacing.hairline,
    borderRadius: radius.pill,
  },
  demoRoleBadgeGreen: {
    backgroundColor: colors.success.text,
  },
  demoRoleBadgeBlue: {
    backgroundColor: leopardPalette.primary,
  },
  demoRoleBadgeSlate: {
    backgroundColor: leopardPalette.textMutedSlate,
  },
  demoRoleBadgeText: {
    ...typeScale.caption2,
    fontWeight: '700',
    color: '#FFFFFF',
  },
  demoCardDesc: {
    ...typeScale.caption1,
    color: '#64748B',
    lineHeight: 16,
    marginBottom: spacing.xxs,
  },

  footerLinkRow: {
    alignItems: 'center',
    borderTopColor: '#E2E8F0',
    borderTopWidth: 1,
    columnGap: spacing.xs,
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'center',
    marginTop: spacing.md,
    minHeight: 48,
    paddingTop: spacing.sm,
  },
  footerPrompt: {
    color: '#64748B',
    ...typeScale.footnote,
  },
  registerAction: {
    justifyContent: 'center',
    minHeight: 44,
    paddingVertical: spacing.xxs,
    paddingHorizontal: spacing.xxs,
  },
  footerLinkAction: {
    color: leopardPalette.primary,
    ...typeScale.subheadline,
    fontWeight: '700',
    textDecorationLine: 'underline',
  },
  termsNote: {
    color: '#94A3B8',
    ...typeScale.caption2,
    textAlign: 'center',
    lineHeight: 16,
    marginTop: spacing.xxs,
    paddingHorizontal: spacing.sm,
  },
  pressed: {
    opacity: 0.88,
    transform: [{ scale: 0.985 }],
  },

  /* OTP Modal Overlay */
  otpModalOverlay: {
    ...StyleSheet.absoluteFill,
    alignItems: 'center',
    justifyContent: 'center',
    padding: spacing.md,
    zIndex: 100,
  },
  otpBackdrop: {
    ...StyleSheet.absoluteFill,
    backgroundColor: 'rgba(15, 23, 42, 0.45)',
  },
  otpModalCard: {
    ...iosContinuousCurve,
    backgroundColor: '#FFFFFF',
    borderColor: '#E2E8F0',
    borderRadius: radius.modal,
    borderWidth: 1,
    elevation: 12,
    maxWidth: 420,
    padding: spacing.lg,
    shadowColor: '#0F172A',
    shadowOffset: { width: 0, height: 12 },
    shadowOpacity: 0.15,
    shadowRadius: 24,
    width: '100%',
  },
  otpHeaderNav: {
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: spacing.md,
  },
  otpNavBack: {
    minHeight: 44,
    justifyContent: 'center',
    paddingVertical: spacing.xxs,
  },
  otpNavBackText: {
    color: leopardPalette.primary,
    ...typeScale.footnote,
    fontWeight: '600',
  },
  otpNavStatus: {
    color: '#64748B',
    ...typeScale.caption2,
    fontWeight: '600',
    letterSpacing: 0.7,
  },
  otpCenterHero: {
    alignItems: 'center',
    marginBottom: spacing.md,
  },
  otpBadge: {
    alignItems: 'center',
    backgroundColor: '#EFF6FF',
    borderColor: '#BFDBFE',
    borderRadius: radius.pill,
    borderWidth: 1.5,
    height: 64,
    justifyContent: 'center',
    marginBottom: spacing.sm,
    width: 64,
  },
  otpBadgeSuccess: {
    backgroundColor: '#F0FDF4',
    borderColor: '#BBF7D0',
  },
  otpBadgeIcon: {
    ...typeScale.title1,
  },
  otpModalTitle: {
    color: '#0F172A',
    ...typeScale.title3,
    fontWeight: '700',
    marginBottom: spacing.xxs,
    textAlign: 'center',
  },
  otpModalDesc: {
    color: '#64748B',
    ...typeScale.footnote,
    lineHeight: 18,
    textAlign: 'center',
  },
  phoneHighlight: {
    color: '#0F172A',
    fontWeight: '700',
    fontVariant: ['tabular-nums'],
  },
  verifyingWrap: {
    alignItems: 'center',
    gap: spacing.xs,
    marginVertical: spacing.sm,
  },
  verifyingText: {
    color: '#64748B',
    ...typeScale.caption1,
    fontWeight: '600',
  },
  otpErrorBox: {
    backgroundColor: '#FEF2F2',
    borderColor: '#FECACA',
    borderRadius: radius.control,
    borderWidth: 1,
    marginTop: spacing.sm,
    padding: spacing.xs + spacing.hairline,
  },
  otpErrorText: {
    color: '#B91C1C',
    ...typeScale.footnote,
    textAlign: 'center',
  },
  otpSuccessBox: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.xs,
    backgroundColor: '#F0FDF4',
    borderColor: '#BBF7D0',
    borderRadius: radius.control,
    borderWidth: 1,
    marginTop: spacing.sm,
    padding: spacing.sm,
  },
  otpSuccessText: {
    flex: 1,
    color: '#15803D',
    ...typeScale.footnote,
    lineHeight: typeScale.footnote.lineHeight,
  },
  otpFooter: {
    marginTop: spacing.md,
    alignItems: 'center',
  },
  resendBtn: {
    minHeight: 44,
    paddingHorizontal: spacing.sm,
    paddingVertical: spacing.xs,
    justifyContent: 'center',
  },
  resendBtnText: {
    color: leopardPalette.primary,
    ...typeScale.footnote,
    fontWeight: '600',
  },
  resendBtnDisabledText: {
    color: '#94A3B8',
  },
});
