import { Platform, StyleSheet } from 'react-native';

import { spacing, typeScale } from '@leopard/mobile-core';

export const styles = StyleSheet.create({
  rootContainer: {
    flex: 1,
    backgroundColor: '#0B1E42',
    ...(Platform.OS === 'web' ? { minHeight: '100dvh' as any } : {}),
  },
  keyboardWrap: {
    flex: 1,
  },
  scrollView: {
    flex: 1,
  },
  scrollContent: {
    alignSelf: 'center',
    flexGrow: 1,
    maxWidth: 480,
    width: '100%',
    justifyContent: 'space-between',
  },
  heroSection: {
    minHeight: 215,
    overflow: 'hidden',
    position: 'relative',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingBottom: 20,
  },
  heroAuraSvg: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
  },
  heroImage: {
    height: '100%',
    width: '100%',
  },
  heroGradient: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
  },
  brandHeader: {
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    width: '100%',
  },
  brandRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    alignSelf: 'center',
  },
  brandEmblem: {
    height: 30,
    width: 70,
    marginRight: -42,
    marginLeft: 32,
    marginTop: -5,
    zIndex: 1,
  },
  brandWordmark: {
    height: 40,
    width: 210,
    shadowColor: '#FFFFFF',
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 0.25,
    shadowRadius: 10,
  },
  driverBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    alignSelf: 'center',
    backgroundColor: 'rgba(56, 189, 248, 0.12)',
    borderColor: 'rgba(56, 189, 248, 0.40)',
    borderRadius: 9999,
    borderWidth: 1,
    paddingHorizontal: 12,
    paddingVertical: 3.5,
    gap: 5,
    marginTop: 4,
  },
  driverBadgeDot: {
    width: 6,
    height: 6,
    borderRadius: 3,
    backgroundColor: '#38BDF8',
  },
  driverBadgeText: {
    color: '#38BDF8',
    fontSize: 11,
    fontWeight: '800',
    letterSpacing: 1.2,
  },
  heroCopy: {
    alignItems: 'center',
    paddingHorizontal: 24,
    marginTop: 12,
  },
  eyebrow: {
    color: '#FDBA74',
    fontSize: typeScale.caption2.fontSize,
    fontWeight: '800',
    letterSpacing: 1.25,
    marginBottom: 7,
  },
  mainTitle: {
    color: '#FFFFFF',
    fontSize: typeScale.title2.fontSize,
    fontWeight: '800',
    letterSpacing: -0.3,
    textAlign: 'center',
    lineHeight: 30,
  },
  subTitle: {
    color: '#CBD5E1',
    fontSize: typeScale.subheadline.fontSize,
    lineHeight: 20,
    marginTop: 5,
    textAlign: 'center',
    maxWidth: 320,
  },
  formCard: {
    backgroundColor: 'rgba(15, 30, 60, 0.72)',
    borderColor: 'rgba(255, 255, 255, 0.10)',
    borderTopLeftRadius: 28,
    borderTopRightRadius: 28,
    borderWidth: 1,
    borderBottomWidth: 0,
    flexGrow: 1,
    paddingHorizontal: 22,
    paddingTop: 24,
    paddingBottom: 24,
    shadowColor: '#020817',
    shadowOffset: { width: 0, height: -8 },
    shadowOpacity: 0.18,
    shadowRadius: 20,
    width: '100%',
  },
  alertBox: {
    backgroundColor: 'rgba(249, 115, 22, 0.13)',
    borderColor: 'rgba(253, 186, 116, 0.48)',
    borderRadius: 12,
    borderWidth: 1,
    marginBottom: 12,
    padding: 10,
  },
  alertText: {
    color: '#FED7AA',
    fontSize: 12,
    lineHeight: 18,
  },
  errorBox: {
    backgroundColor: 'rgba(239, 68, 68, 0.14)',
    borderColor: 'rgba(248, 113, 113, 0.46)',
    borderRadius: 12,
    borderWidth: 1,
    marginBottom: 12,
    padding: 10,
  },
  errorText: {
    color: '#FECACA',
    fontSize: 12,
    lineHeight: 18,
  },
  fieldSection: {
    marginBottom: 16,
  },
  labelRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 8,
  },
  fieldLabel: {
    color: '#FFFFFF',
    fontSize: typeScale.subheadline.fontSize,
    fontWeight: '800',
  },
  validBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.xxs,
    backgroundColor: '#DCFCE7',
    paddingHorizontal: spacing.xs,
    paddingVertical: spacing.hairline,
    borderRadius: 999,
  },
  validText: {
    fontSize: typeScale.caption2.fontSize,
    color: '#15803D',
    fontWeight: '700',
  },
  fieldHint: {
    color: '#CBD5E1',
    fontSize: typeScale.caption1.fontSize,
    lineHeight: typeScale.caption1.lineHeight,
    marginTop: spacing.xs,
    fontWeight: '500',
  },
  inputRow: {
    alignItems: 'center',
    backgroundColor: '#132B52',
    borderColor: 'rgba(255, 255, 255, 0.18)',
    borderRadius: 14,
    borderWidth: 1.5,
    flexDirection: 'row',
    minHeight: 54,
    height: 54,
    paddingLeft: 8,
    paddingRight: 6,
    gap: 4,
    shadowColor: '#020817',
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.10,
    shadowRadius: 10,
    elevation: 2,
  },
  inputRowFocused: {
    borderColor: '#38BDF8',
    shadowColor: '#0284C7',
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 0.35,
    shadowRadius: 8,
    elevation: 3,
  },
  inputRowValid: {
    borderColor: 'rgba(56, 189, 248, 0.65)',
  },
  countryBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 5,
    backgroundColor: 'rgba(255, 255, 255, 0.08)',
    paddingHorizontal: 8,
    paddingVertical: 6,
    borderRadius: 8,
  },
  countryCode: {
    fontSize: typeScale.subheadline.fontSize,
    fontWeight: '700',
    color: '#FFFFFF',
    fontVariant: ['tabular-nums'],
  },
  countryChevron: {
    fontSize: typeScale.caption2.fontSize,
    color: '#94A3B8',
    fontWeight: '700',
    marginTop: -1,
  },
  badgeDivider: {
    width: 1,
    height: 22,
    backgroundColor: 'rgba(255, 255, 255, 0.16)',
    marginHorizontal: 4,
  },
  textInput: {
    color: '#FFFFFF',
    flex: 1,
    fontSize: 16,
    fontWeight: '700',
    fontVariant: ['tabular-nums'],
    letterSpacing: 0.5,
    minWidth: 0,
    paddingVertical: 0,
    height: '100%',
    ...Platform.select({
      web: {
        outlineStyle: 'none',
        outlineWidth: 0,
      } as any,
    }),
  },
  clearBtn: {
    paddingHorizontal: spacing.xs,
    paddingVertical: spacing.hairline,
    justifyContent: 'center',
    alignItems: 'center',
  },
  primaryBtn: {
    alignItems: 'center',
    backgroundColor: '#0284C7',
    borderRadius: 16,
    justifyContent: 'center',
    minHeight: 54,
    height: 54,
    paddingHorizontal: 16,
    shadowColor: '#0284C7',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.35,
    shadowRadius: 12,
    elevation: 4,
  },
  primaryBtnDisabled: {
    backgroundColor: 'rgba(2, 132, 199, 0.16)',
    borderColor: 'rgba(56, 189, 248, 0.35)',
    borderWidth: 1.5,
    shadowOpacity: 0,
    elevation: 0,
  },
  primaryBtnText: {
    color: '#FFFFFF',
    fontSize: 16,
    fontWeight: '800',
    letterSpacing: 0.3,
    textAlign: 'center',
  },
  primaryBtnDisabledText: {
    color: '#7DD3FC',
    fontSize: 15,
    fontWeight: '800',
    letterSpacing: 0.2,
  },
  loadingRow: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 10,
  },
  orSection: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 12,
    marginVertical: 16,
  },
  orLine: {
    backgroundColor: 'rgba(255, 255, 255, 0.18)',
    flex: 1,
    height: 1,
  },
  orText: {
    color: '#CBD5E1',
    fontSize: 12,
    fontWeight: '700',
  },
  googleBtn: {
    alignItems: 'center',
    backgroundColor: 'rgba(255, 255, 255, 0.08)',
    borderColor: 'rgba(255, 255, 255, 0.20)',
    borderRadius: 16,
    borderWidth: 1.5,
    flexDirection: 'row',
    gap: 12,
    justifyContent: 'center',
    minHeight: 52,
    height: 52,
    padding: 10,
  },
  googleIconWrap: {
    alignItems: 'center',
    backgroundColor: '#FFFFFF',
    borderColor: '#E3E8EF',
    borderRadius: 999,
    borderWidth: 1,
    height: 28,
    justifyContent: 'center',
    width: 28,
  },
  googleG: {
    color: '#4285F4',
    fontSize: 20,
    fontWeight: '800',
    lineHeight: 23,
  },
  googleBtnText: {
    color: '#FFFFFF',
    flexShrink: 1,
    fontSize: 15,
    fontWeight: '700',
    textAlign: 'center',
  },
  btnDisabled: {
    backgroundColor: 'rgba(255, 255, 255, 0.035)',
    opacity: 0.58,
  },
  firebaseNote: {
    color: '#CBD5E1',
    fontSize: 12,
    lineHeight: 18,
    marginTop: 8,
    textAlign: 'center',
  },
  recaptcha: {
    height: 0,
    width: 0,
  },
  footerLinkRow: {
    alignItems: 'center',
    borderTopColor: 'rgba(255, 255, 255, 0.12)',
    borderTopWidth: 1,
    columnGap: 8,
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'center',
    marginTop: 20,
    minHeight: 52,
    paddingTop: 16,
  },
  footerPrompt: {
    color: '#CBD5E1',
    fontSize: 13,
    fontWeight: '500',
  },
  registerAction: {
    justifyContent: 'center',
    minHeight: 48,
    paddingVertical: 6,
    paddingHorizontal: 4,
  },
  footerLinkAction: {
    color: '#38BDF8',
    fontSize: typeScale.subheadline.fontSize,
    fontWeight: '800',
    textDecorationLine: 'underline',
  },
  pressed: {
    opacity: 0.86,
    transform: [{ scale: 0.98 }],
  },
  otpModalOverlay: {
    ...StyleSheet.absoluteFill,
    alignItems: 'center',
    justifyContent: 'center',
    padding: 20,
    zIndex: 100,
  },
  otpBackdrop: {
    ...StyleSheet.absoluteFill,
    backgroundColor: 'rgba(16, 42, 67, 0.58)',
  },
  otpModalCard: {
    backgroundColor: '#FFFFFF',
    borderColor: '#DCE4EC',
    borderRadius: 24,
    borderWidth: 1,
    elevation: 12,
    maxWidth: 400,
    padding: 24,
    shadowColor: '#102A43',
    shadowOffset: { width: 0, height: 12 },
    shadowOpacity: 0.2,
    shadowRadius: 24,
    width: '100%',
  },
  otpHeaderNav: {
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 16,
  },
  otpNavBack: {
    minHeight: 44,
    justifyContent: 'center',
    paddingVertical: 4,
  },
  otpNavBackText: {
    color: '#102A43',
    fontSize: 13,
    fontWeight: '800',
  },
  otpNavStatus: {
    color: '#64748B',
    fontSize: 11,
    fontWeight: '800',
    letterSpacing: 0.7,
  },
  otpCenterHero: {
    alignItems: 'center',
    marginBottom: 20,
  },
  otpBadge: {
    alignItems: 'center',
    backgroundColor: '#EEF4F8',
    borderColor: '#CAD6E1',
    borderRadius: 32,
    borderWidth: 1.5,
    height: 64,
    justifyContent: 'center',
    marginBottom: 12,
    width: 64,
  },
  otpBadgeSuccess: {
    backgroundColor: '#E8F7EF',
    borderColor: '#6FCF97',
  },
  otpBadgeIcon: {
    fontSize: typeScale.title1.fontSize,
  },
  otpModalTitle: {
    color: '#102A43',
    fontSize: typeScale.body.fontSize,
    fontWeight: '900',
    marginBottom: 6,
    textAlign: 'center',
  },
  otpModalDesc: {
    color: '#526375',
    fontSize: 13,
    lineHeight: 18,
    textAlign: 'center',
  },
  phoneHighlight: {
    color: '#102A43',
    fontWeight: '800',
  },
  verifyingWrap: {
    alignItems: 'center',
    gap: 8,
    marginVertical: 12,
  },
  verifyingText: {
    color: '#526375',
    fontSize: 12,
  },
  otpErrorBox: {
    backgroundColor: '#FFF0EF',
    borderColor: '#F3B8B4',
    borderRadius: 12,
    borderWidth: 1,
    marginTop: 12,
    padding: 10,
  },
  otpErrorText: {
    color: '#B42318',
    fontSize: 13,
    textAlign: 'center',
  },
  otpSuccessBox: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.xs,
    backgroundColor: '#E8F7EF',
    borderColor: '#9FE1B7',
    borderRadius: 12,
    borderWidth: 1,
    marginTop: spacing.sm,
    padding: spacing.sm,
  },
  otpSuccessText: {
    flex: 1,
    color: '#167A3A',
    fontSize: typeScale.footnote.fontSize,
    lineHeight: typeScale.footnote.lineHeight,
  },
  otpFooter: {
    marginTop: 18,
    alignItems: 'center',
  },
  resendBtn: {
    minHeight: 44,
    paddingHorizontal: 12,
    paddingVertical: 8,
    justifyContent: 'center',
  },
  resendBtnText: {
    color: '#102A43',
    fontSize: 13,
    fontWeight: '800',
  },
  resendBtnDisabledText: {
    color: '#8A98A7',
  },
});
