import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  rootContainer: {
    flex: 1,
    backgroundColor: '#0B1E42',
  },
  keyboardWrap: {
    flex: 1,
  },
  scrollView: {
    flex: 1,
  },
  scrollContent: {
    alignSelf: 'center',
    flexGrow: 1,
    maxWidth: 480,
    width: '100%',
  },
  heroSection: {
    height: 270,
    overflow: 'hidden',
    position: 'relative',
  },
  heroImage: {
    height: '100%',
    width: '100%',
  },
  heroGradient: {
    ...StyleSheet.absoluteFill,
  },
  brandHeader: {
    left: 18,
    alignItems: 'center',
    flexDirection: 'row',
    gap: 12,
    justifyContent: 'space-between',
    position: 'absolute',
    right: 18,
    zIndex: 1,
  },
  cardBrandRow: {
    alignItems: 'center',
    backgroundColor: 'rgba(255, 255, 255, 0.94)',
    borderColor: 'rgba(255, 255, 255, 0.72)',
    borderRadius: 12,
    borderWidth: 1,
    flexDirection: 'row',
    flexShrink: 1,
    gap: 5,
    paddingHorizontal: 9,
    paddingVertical: 5,
  },
  cardEmblemImage: {
    height: 25,
    width: 40,
  },
  cardBrandNameImage: {
    height: 27,
    width: 95,
  },
  driverLabel: {
    backgroundColor: '#F97316',
    borderColor: 'rgba(255, 255, 255, 0.35)',
    borderRadius: 999,
    borderWidth: 1,
    paddingHorizontal: 12,
    paddingVertical: 7,
  },
  driverLabelText: {
    color: '#FFFFFF',
    fontSize: 10,
    fontWeight: '800',
    letterSpacing: 1.3,
  },
  heroCopy: {
    bottom: 23,
    left: 22,
    position: 'absolute',
    right: 22,
  },
  eyebrow: {
    color: '#FDBA74',
    fontSize: 10,
    fontWeight: '800',
    letterSpacing: 1.25,
    marginBottom: 7,
  },
  mainTitle: {
    color: '#FFFFFF',
    fontSize: 28,
    fontWeight: '800',
    letterSpacing: -0.3,
    lineHeight: 34,
  },
  subTitle: {
    color: '#D8E3F0',
    fontSize: 13,
    lineHeight: 19,
    marginTop: 5,
    maxWidth: 300,
  },
  formCard: {
    backgroundColor: '#0B1E42',
    borderTopColor: 'rgba(255, 255, 255, 0.10)',
    borderTopLeftRadius: 26,
    borderTopRightRadius: 26,
    borderTopWidth: 1,
    flexGrow: 1,
    marginTop: -4,
    paddingHorizontal: 22,
    paddingTop: 16,
    shadowColor: '#020817',
    shadowOffset: { width: 0, height: -8 },
    shadowOpacity: 0.14,
    shadowRadius: 18,
    width: '100%',
  },
  alertBox: {
    backgroundColor: 'rgba(249, 115, 22, 0.13)',
    borderColor: 'rgba(253, 186, 116, 0.48)',
    borderRadius: 12,
    borderWidth: 1,
    marginBottom: 12,
    padding: 10,
  },
  alertText: {
    color: '#FED7AA',
    fontSize: 12,
    lineHeight: 18,
  },
  errorBox: {
    backgroundColor: 'rgba(239, 68, 68, 0.14)',
    borderColor: 'rgba(248, 113, 113, 0.46)',
    borderRadius: 12,
    borderWidth: 1,
    marginBottom: 12,
    padding: 10,
  },
  errorText: {
    color: '#FECACA',
    fontSize: 12,
    lineHeight: 18,
  },
  fieldSection: {
    marginBottom: 14,
  },
  fieldLabel: {
    color: '#F8FAFC',
    fontSize: 13,
    fontWeight: '700',
    marginBottom: 7,
  },
  fieldHint: {
    color: '#9FB0C7',
    fontSize: 11,
    lineHeight: 16,
    marginTop: 6,
  },
  inputRow: {
    alignItems: 'center',
    backgroundColor: '#142B50',
    borderColor: '#385274',
    borderRadius: 14,
    borderWidth: 1.5,
    flexDirection: 'row',
    minHeight: 54,
    paddingLeft: 14,
    paddingRight: 4,
    shadowColor: '#020817',
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.04,
    shadowRadius: 10,
    elevation: 1,
  },
  inputRowFocused: {
    borderColor: '#FDBA74',
    shadowOpacity: 0.22,
  },
  inputRowValid: {
    borderColor: '#7E93AD',
  },
  countryPill: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 7,
  },
  countryCodeText: {
    color: '#F8FAFC',
    fontSize: 14,
    fontWeight: '700',
  },
  inputDivider: {
    backgroundColor: '#385274',
    height: 22,
    marginHorizontal: 11,
    width: 1,
  },
  textInput: {
    color: '#FFFFFF',
    flex: 1,
    fontSize: 16,
    fontWeight: '600',
    minWidth: 0,
    paddingVertical: 15,
  },
  clearBtn: {
    alignItems: 'center',
    height: 44,
    justifyContent: 'center',
    width: 44,
  },
  clearBtnText: {
    color: '#AFC0D4',
    fontSize: 14,
    fontWeight: '800',
  },
  primaryBtn: {
    alignItems: 'center',
    backgroundColor: '#F97316',
    borderRadius: 14,
    justifyContent: 'center',
    minHeight: 52,
    padding: 12,
    shadowColor: '#020817',
    shadowOffset: { width: 0, height: 5 },
    shadowOpacity: 0.2,
    shadowRadius: 12,
    elevation: 3,
  },
  primaryBtnDisabled: {
    backgroundColor: '#344A6B',
    shadowOpacity: 0,
    elevation: 0,
  },
  primaryBtnText: {
    color: '#FFFFFF',
    fontSize: 15,
    fontWeight: '800',
    letterSpacing: 0,
    textAlign: 'center',
  },
  loadingRow: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 10,
  },
  orSection: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 12,
    marginVertical: 12,
  },
  orLine: {
    backgroundColor: 'rgba(255, 255, 255, 0.14)',
    flex: 1,
    height: 1,
  },
  orText: {
    color: '#91A3BB',
    fontSize: 11,
    fontWeight: '700',
  },
  googleBtn: {
    alignItems: 'center',
    backgroundColor: 'rgba(255, 255, 255, 0.06)',
    borderColor: '#40597B',
    borderRadius: 14,
    borderWidth: 1,
    flexDirection: 'row',
    gap: 10,
    justifyContent: 'center',
    minHeight: 50,
    padding: 10,
  },
  googleIconWrap: {
    alignItems: 'center',
    backgroundColor: '#FFFFFF',
    borderColor: '#E3E8EF',
    borderRadius: 999,
    borderWidth: 1,
    height: 28,
    justifyContent: 'center',
    width: 28,
  },
  googleG: {
    color: '#4285F4',
    fontSize: 20,
    fontWeight: '800',
    lineHeight: 23,
  },
  googleBtnText: {
    color: '#F8FAFC',
    flexShrink: 1,
    fontSize: 14,
    fontWeight: '700',
    textAlign: 'center',
  },
  btnDisabled: {
    backgroundColor: 'rgba(255, 255, 255, 0.035)',
    opacity: 0.58,
  },
  firebaseNote: {
    color: '#9FB0C7',
    fontSize: 11,
    lineHeight: 16,
    marginTop: 7,
    textAlign: 'center',
  },
  recaptcha: {
    height: 0,
    width: 0,
  },
  demoArea: {
    marginTop: 0,
  },
  demoRow: {
    flexDirection: 'row',
    gap: 10,
  },
  demoBtnPrimary: {
    alignItems: 'center',
    backgroundColor: 'rgba(249, 115, 22, 0.14)',
    borderColor: 'rgba(253, 186, 116, 0.4)',
    borderRadius: 12,
    borderWidth: 1,
    flexDirection: 'row',
    flex: 1,
    gap: 12,
    minHeight: 50,
    padding: 9,
  },
  demoBtnPrimaryTitle: {
    color: '#FFEDD5',
    fontSize: 12,
    fontWeight: '800',
  },
  demoBtnPrimarySubtitle: {
    color: '#FDBA74',
    fontSize: 10,
    lineHeight: 14,
  },
  demoBtnSecondary: {
    alignItems: 'center',
    backgroundColor: 'rgba(255, 255, 255, 0.05)',
    borderColor: '#40597B',
    borderRadius: 12,
    borderWidth: 1,
    flexDirection: 'row',
    flex: 1,
    gap: 12,
    minHeight: 50,
    padding: 9,
  },
  demoBtnSecTitle: {
    color: '#E5EDF6',
    fontSize: 12,
    fontWeight: '800',
  },
  demoBtnSecSubtitle: {
    color: '#91A3BB',
    fontSize: 10,
    lineHeight: 14,
  },
  footerLinkRow: {
    alignItems: 'center',
    borderTopColor: 'rgba(255, 255, 255, 0.10)',
    borderTopWidth: 1,
    columnGap: 6,
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'center',
    marginTop: 'auto',
    minHeight: 45,
    paddingTop: 8,
  },
  footerPrompt: {
    color: '#9FB0C7',
    fontSize: 12,
  },
  registerAction: {
    justifyContent: 'center',
    minHeight: 44,
  },
  footerLinkAction: {
    color: '#FDBA74',
    fontSize: 12,
    fontWeight: '800',
    textDecorationLine: 'underline',
  },
  pressed: {
    opacity: 0.86,
    transform: [{ scale: 0.98 }],
  },
  otpModalOverlay: {
    ...StyleSheet.absoluteFill,
    alignItems: 'center',
    justifyContent: 'center',
    padding: 20,
    zIndex: 100,
  },
  otpBackdrop: {
    ...StyleSheet.absoluteFill,
    backgroundColor: 'rgba(16, 42, 67, 0.58)',
  },
  otpModalCard: {
    backgroundColor: '#FFFFFF',
    borderColor: '#DCE4EC',
    borderRadius: 24,
    borderWidth: 1,
    elevation: 12,
    maxWidth: 400,
    padding: 24,
    shadowColor: '#102A43',
    shadowOffset: { width: 0, height: 12 },
    shadowOpacity: 0.2,
    shadowRadius: 24,
    width: '100%',
  },
  otpHeaderNav: {
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 16,
  },
  otpNavBack: {
    minHeight: 44,
    justifyContent: 'center',
    paddingVertical: 4,
  },
  otpNavBackText: {
    color: '#102A43',
    fontSize: 13,
    fontWeight: '800',
  },
  otpNavStatus: {
    color: '#64748B',
    fontSize: 11,
    fontWeight: '800',
    letterSpacing: 0.7,
  },
  otpCenterHero: {
    alignItems: 'center',
    marginBottom: 20,
  },
  otpBadge: {
    alignItems: 'center',
    backgroundColor: '#EEF4F8',
    borderColor: '#CAD6E1',
    borderRadius: 32,
    borderWidth: 1.5,
    height: 64,
    justifyContent: 'center',
    marginBottom: 12,
    width: 64,
  },
  otpBadgeSuccess: {
    backgroundColor: '#E8F7EF',
    borderColor: '#6FCF97',
  },
  otpBadgeIcon: {
    fontSize: 26,
  },
  otpModalTitle: {
    color: '#102A43',
    fontSize: 18,
    fontWeight: '900',
    marginBottom: 6,
    textAlign: 'center',
  },
  otpModalDesc: {
    color: '#526375',
    fontSize: 13,
    lineHeight: 18,
    textAlign: 'center',
  },
  phoneHighlight: {
    color: '#102A43',
    fontWeight: '800',
  },
  verifyingWrap: {
    alignItems: 'center',
    gap: 8,
    marginVertical: 12,
  },
  verifyingText: {
    color: '#526375',
    fontSize: 12,
  },
  otpErrorBox: {
    backgroundColor: '#FFF0EF',
    borderColor: '#F3B8B4',
    borderRadius: 12,
    borderWidth: 1,
    marginTop: 12,
    padding: 10,
  },
  otpErrorText: {
    color: '#B42318',
    fontSize: 13,
    textAlign: 'center',
  },
  otpSuccessBox: {
    backgroundColor: '#E8F7EF',
    borderColor: '#9FE1B7',
    borderRadius: 12,
    borderWidth: 1,
    marginTop: 12,
    padding: 10,
  },
  otpSuccessText: {
    color: '#167A3A',
    fontSize: 13,
    textAlign: 'center',
  },
  otpFooter: {
    marginTop: 18,
    alignItems: 'center',
  },
  resendBtn: {
    minHeight: 44,
    paddingHorizontal: 12,
    paddingVertical: 8,
    justifyContent: 'center',
  },
  resendBtnText: {
    color: '#102A43',
    fontSize: 13,
    fontWeight: '800',
  },
  resendBtnDisabledText: {
    color: '#8A98A7',
  },
});
